### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by aburd** [tokyomovie/tokyomovie#6]
We need a basic theme to define our color pallete.

- https://tailwindcss.com/docs/configuration
- https://tailwindcss.com/docs/theme
- https://tailwindcss.com/docs/customizing-colors#default-color-palette

At least, we need some basic colors to guide us in how the pages look. I'm not an expert, but I would expect to have the following colors in the config

- a default text color
- a secondary text color, for say notes or something
- a color for hyperlinks
- color for text which denotes success
- a color for which denotes error
- a primary background color
- a secondary background color

**Comment by scootyboots** [comment]
in case anyone would like some inspo, here's the movie theater i worked at in highschool
![image](https://github.com/user-attachments/assets/be0817bf-ffa3-4d08-834f-b56ab741425b)
![image](https://github.com/user-attachments/assets/3c41b842-c2eb-474e-98fe-a3e4fdff9503)

**Comment by aburd** [comment]
Oh damn, kind of 80s fabulous, the movie barn

**Comment by aburd** [comment]
Some cool color choices here

![youkai](https://github.com/user-attachments/assets/6babe7f7-d12c-4387-815c-4d8868298c14)
![youkai2](https://github.com/user-attachments/assets/086f7256-e832-42ba-903e-4683c4cf51fd)
![youkai3](https://github.com/user-attachments/assets/2e539925-0377-47a1-8ed3-efd37bf74d66)
![youkai4](https://github.com/user-attachments/assets/d2c2cc1e-8e48-4456-b23c-bddebe42d543)

**Comment by aburd** [comment]
Since @scootyboots pretty much setup some basic color palletes, I will close this.
